[package]
name = "wapc"
version = "0.2.2"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
description = "Rust WebAssembly Host Runtime Conforming to the waPC Standard"
license = "Apache-2.0"
homepage = "https://github.com/wapc"
documentation = "https://docs.rs/wapc"
readme = "README.md"
keywords = ["sdk", "wapc", "webassembly", "wasm", "wasi"]
categories = ["wasm", "api-bindings"]
exclude = [".assets"]

[badges]
travis-ci = { repository = "wapc/wapc-rust", branch = "master" }

[dependencies]
log = "0.4.8"
env_logger = "0.7"
lazy_static = "1.4.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.46"
wasmtime = "0.12.0"
anyhow = "1.0"